# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const1.xdc

# IP: ip/div_gen_hex_2_dec/div_gen_hex_2_dec.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_hex_2_dec || ORIG_REF_NAME==div_gen_hex_2_dec} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/system/ip/system_ps_pl_axi4_0_0/system_ps_pl_axi4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps_pl_axi4_0_0 || ORIG_REF_NAME==system_ps_pl_axi4_0_0} -quiet] -quiet

# IP: bd/system/ip/system_TOP_0_0/system_TOP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_TOP_0_0 || ORIG_REF_NAME==system_TOP_0_0} -quiet] -quiet

# IP: ip/div_gen_hex_2_dec/div_gen_hex_2_dec.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_hex_2_dec || ORIG_REF_NAME==div_gen_hex_2_dec} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: d:/ASUS-PC/Desktop/Mini_ctrl_brd_zynq_v1.1/Mini_ctrl_brd_zynq_v1.1.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: d:/ASUS-PC/Desktop/Mini_ctrl_brd_zynq_v1.1/Mini_ctrl_brd_zynq_v1.1.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/ASUS-PC/Desktop/Mini_ctrl_brd_zynq_v1.1/Mini_ctrl_brd_zynq_v1.1.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/ASUS-PC/Desktop/Mini_ctrl_brd_zynq_v1.1/Mini_ctrl_brd_zynq_v1.1.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/ASUS-PC/Desktop/Mini_ctrl_brd_zynq_v1.1/Mini_ctrl_brd_zynq_v1.1.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: d:/ASUS-PC/Desktop/Mini_ctrl_brd_zynq_v1.1/Mini_ctrl_brd_zynq_v1.1.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: d:/ASUS-PC/Desktop/Mini_ctrl_brd_zynq_v1.1/Mini_ctrl_brd_zynq_v1.1.gen/sources_1/bd/system/system_ooc.xdc
