set_property PACKAGE_PIN L17 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN L16 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN J14 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN K14 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
