set_property PACKAGE_PIN L17 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN L16 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN J14 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN K14 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[31]}]
set_property PACKAGE_PIN M14 [get_ports {GPIO_0_0_tri_io[4]}]
set_property PACKAGE_PIN N16 [get_ports {GPIO_0_0_tri_io[5]}]
set_property PACKAGE_PIN V8 [get_ports {GPIO_0_0_tri_io[6]}]
set_property PACKAGE_PIN V7 [get_ports {GPIO_0_0_tri_io[7]}]
set_property PACKAGE_PIN U7 [get_ports {GPIO_0_0_tri_io[8]}]
set_property PACKAGE_PIN U5 [get_ports {GPIO_0_0_tri_io[9]}]
set_property PACKAGE_PIN T5 [get_ports {GPIO_0_0_tri_io[10]}]
set_property PACKAGE_PIN N20 [get_ports {GPIO_0_0_tri_io[11]}]
set_property PACKAGE_PIN P20 [get_ports {GPIO_0_0_tri_io[12]}]
set_property PACKAGE_PIN L20 [get_ports {GPIO_0_0_tri_io[13]}]
set_property PACKAGE_PIN A20 [get_ports {GPIO_0_0_tri_io[14]}]
set_property PACKAGE_PIN F16 [get_ports {GPIO_0_0_tri_io[15]}]
set_property PACKAGE_PIN N15 [get_ports {GPIO_0_0_tri_io[16]}]
set_property PACKAGE_PIN L14 [get_ports {GPIO_0_0_tri_io[17]}]
set_property PACKAGE_PIN L15 [get_ports {GPIO_0_0_tri_io[18]}]
set_property PACKAGE_PIN E17 [get_ports {GPIO_0_0_tri_io[19]}]
set_property PACKAGE_PIN G14 [get_ports {GPIO_0_0_tri_io[20]}]
set_property PACKAGE_PIN G17 [get_ports {GPIO_0_0_tri_io[21]}]
set_property PACKAGE_PIN D18 [get_ports {GPIO_0_0_tri_io[22]}]
set_property PACKAGE_PIN J15 [get_ports {GPIO_0_0_tri_io[23]}]
set_property PACKAGE_PIN M17 [get_ports {GPIO_0_0_tri_io[24]}]
set_property PACKAGE_PIN U20 [get_ports {GPIO_0_0_tri_io[25]}]
set_property PACKAGE_PIN K19 [get_ports {GPIO_0_0_tri_io[26]}]
set_property PACKAGE_PIN J19 [get_ports {GPIO_0_0_tri_io[27]}]
set_property PACKAGE_PIN G19 [get_ports {GPIO_0_0_tri_io[28]}]
set_property PACKAGE_PIN G20 [get_ports {GPIO_0_0_tri_io[29]}]
set_property PACKAGE_PIN J20 [get_ports {GPIO_0_0_tri_io[30]}]
set_property PACKAGE_PIN H20 [get_ports {GPIO_0_0_tri_io[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports UART_1_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_0_txd]
set_property PACKAGE_PIN K16 [get_ports UART_1_0_rxd]
set_property PACKAGE_PIN M15 [get_ports UART_1_0_txd]





create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/blk_mem_gen_0/U0/doutb[0]} {system_i/blk_mem_gen_0/U0/doutb[1]} {system_i/blk_mem_gen_0/U0/doutb[2]} {system_i/blk_mem_gen_0/U0/doutb[3]} {system_i/blk_mem_gen_0/U0/doutb[4]} {system_i/blk_mem_gen_0/U0/doutb[5]} {system_i/blk_mem_gen_0/U0/doutb[6]} {system_i/blk_mem_gen_0/U0/doutb[7]} {system_i/blk_mem_gen_0/U0/doutb[8]} {system_i/blk_mem_gen_0/U0/doutb[9]} {system_i/blk_mem_gen_0/U0/doutb[10]} {system_i/blk_mem_gen_0/U0/doutb[11]} {system_i/blk_mem_gen_0/U0/doutb[12]} {system_i/blk_mem_gen_0/U0/doutb[13]} {system_i/blk_mem_gen_0/U0/doutb[14]} {system_i/blk_mem_gen_0/U0/doutb[15]} {system_i/blk_mem_gen_0/U0/doutb[16]} {system_i/blk_mem_gen_0/U0/doutb[17]} {system_i/blk_mem_gen_0/U0/doutb[18]} {system_i/blk_mem_gen_0/U0/doutb[19]} {system_i/blk_mem_gen_0/U0/doutb[20]} {system_i/blk_mem_gen_0/U0/doutb[21]} {system_i/blk_mem_gen_0/U0/doutb[22]} {system_i/blk_mem_gen_0/U0/doutb[23]} {system_i/blk_mem_gen_0/U0/doutb[24]} {system_i/blk_mem_gen_0/U0/doutb[25]} {system_i/blk_mem_gen_0/U0/doutb[26]} {system_i/blk_mem_gen_0/U0/doutb[27]} {system_i/blk_mem_gen_0/U0/doutb[28]} {system_i/blk_mem_gen_0/U0/doutb[29]} {system_i/blk_mem_gen_0/U0/doutb[30]} {system_i/blk_mem_gen_0/U0/doutb[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 11 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/blk_mem_gen_0/U0/addrb[2]} {system_i/blk_mem_gen_0/U0/addrb[3]} {system_i/blk_mem_gen_0/U0/addrb[4]} {system_i/blk_mem_gen_0/U0/addrb[5]} {system_i/blk_mem_gen_0/U0/addrb[6]} {system_i/blk_mem_gen_0/U0/addrb[7]} {system_i/blk_mem_gen_0/U0/addrb[8]} {system_i/blk_mem_gen_0/U0/addrb[9]} {system_i/blk_mem_gen_0/U0/addrb[10]} {system_i/blk_mem_gen_0/U0/addrb[11]} {system_i/blk_mem_gen_0/U0/addrb[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list system_i/blk_mem_gen_0/U0/enb]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
