set_property SRC_FILE_INFO {cfile:D:/ASUS-PC/Desktop/temporary/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.srcs/constrs_1/new/Navigator.xdc rfile:../../../Mini_ctrl_brd_zynq.srcs/constrs_1/new/Navigator.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports {GPIO_0_0_tri_io[3]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports {GPIO_0_0_tri_io[2]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports {GPIO_0_0_tri_io[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports {GPIO_0_0_tri_io[0]}]
